// Chataigne module -> Deferlante visuals (Godot).
// Generated by tools/build_chataigne_module.py, do not edit by hand.

function init() {
	script.log("Deferlante module ready");
}

function globalSpeed(value) {
	local.send("/deferlante/global/speed", value);
}

function globalChaos(value) {
	local.send("/deferlante/global/chaos", value);
}

function globalRandomizer(value) {
	local.send("/deferlante/global/randomizer", value);
}

function globalGlow(value) {
	local.send("/deferlante/global/glow", value);
}

function globalRecall(value) {
	local.send("/deferlante/global/recall", value);
}

function globalPanel(value) {
	local.send("/deferlante/global/panel", value);
}

function globalAutodim(value) {
	local.send("/deferlante/global/autodim", value);
}

function colorMode(value) {
	local.send("/deferlante/color/mode", value);
}

function colorSaturation(value) {
	local.send("/deferlante/color/saturation", value);
}

function colorRed(value) {
	local.send("/deferlante/color/red", value);
}

function colorGreen(value) {
	local.send("/deferlante/color/green", value);
}

function colorBlue(value) {
	local.send("/deferlante/color/blue", value);
}

function mirrorEffect(value) {
	local.send("/deferlante/mirror/effect", value);
}

function mirrorSegments(value) {
	local.send("/deferlante/mirror/segments", value);
}

function mirrorRotation(value) {
	local.send("/deferlante/mirror/rotation", value);
}

function blurAmount(value) {
	local.send("/deferlante/blur/amount", value);
}

function lasersCount(value) {
	local.send("/deferlante/lasers/count", value);
}

function lasersWidth(value) {
	local.send("/deferlante/lasers/width", value);
}

function lasersLength(value) {
	local.send("/deferlante/lasers/length", value);
}

function lasersSpin(value) {
	local.send("/deferlante/lasers/spin", value);
}

function lasersParallel(value) {
	local.send("/deferlante/lasers/parallel", value);
}

function lasersScroll(value) {
	local.send("/deferlante/lasers/scroll", value);
}

function spotRadius(value) {
	local.send("/deferlante/spot/radius", value);
}

function spotPulse(value) {
	local.send("/deferlante/spot/pulse", value);
}

function spotWidth(value) {
	local.send("/deferlante/spot/width", value);
}

function spotSpeed(value) {
	local.send("/deferlante/spot/speed", value);
}

function spotHold(value) {
	local.send("/deferlante/spot/hold", value);
}

function spotShake(value) {
	local.send("/deferlante/spot/shake", value);
}

function spotFrequency(value) {
	local.send("/deferlante/spot/frequency", value);
}

function spotSpread(value) {
	local.send("/deferlante/spot/spread", value);
}

function spotArcs(value) {
	local.send("/deferlante/spot/arcs", value);
}

function spotLength(value) {
	local.send("/deferlante/spot/length", value);
}

function spotSpin(value) {
	local.send("/deferlante/spot/spin", value);
}

function spotGlitch(value) {
	local.send("/deferlante/spot/glitch", value);
}

function spotManual(value) {
	local.send("/deferlante/spot/manual", value);
}

function spotTrack(value) {
	local.send("/deferlante/spot/track", value);
}

function spotHandback(value) {
	local.send("/deferlante/spot/handback", value);
}

function audioReactivity(value) {
	local.send("/deferlante/audio/reactivity", value);
}

function audioPunch(value) {
	local.send("/deferlante/audio/punch", value);
}

function audioSpot(value) {
	local.send("/deferlante/audio/spot", value);
}

function audioWarp(value) {
	local.send("/deferlante/audio/warp", value);
}

function audioLasers(value) {
	local.send("/deferlante/audio/lasers", value);
}

function audioSphere(value) {
	local.send("/deferlante/audio/sphere", value);
}

function audioRandomizer(value) {
	local.send("/deferlante/audio/randomizer", value);
}

function sphereCount(value) {
	local.send("/deferlante/sphere/count", value);
}

function sphereSize(value) {
	local.send("/deferlante/sphere/size", value);
}

function sphereSides(value) {
	local.send("/deferlante/sphere/sides", value);
}

function sphereRadius(value) {
	local.send("/deferlante/sphere/radius", value);
}

function sphereSpin(value) {
	local.send("/deferlante/sphere/spin", value);
}

function sphereDepth(value) {
	local.send("/deferlante/sphere/depth", value);
}

function sphereWidth(value) {
	local.send("/deferlante/sphere/width", value);
}

function sphereGlass(value) {
	local.send("/deferlante/sphere/glass", value);
}

function warpCount(value) {
	local.send("/deferlante/warp/count", value);
}

function warpSpeed(value) {
	local.send("/deferlante/warp/speed", value);
}

function warpStreak(value) {
	local.send("/deferlante/warp/streak", value);
}

function warpWidth(value) {
	local.send("/deferlante/warp/width", value);
}

function warpSpread(value) {
	local.send("/deferlante/warp/spread", value);
}

function recallPreset(slot) {
	local.send("/deferlante/preset/recall", slot);
}

function savePreset(slot) {
	local.send("/deferlante/preset/save", slot);
}

// The colour picker arrives as an array [r, g, b, a].
function colorRgb(color) {
	local.send("/deferlante/color/rgb", color[0], color[1], color[2]);
}

function shuffleGlobal(value) {
	local.send("/deferlante/shuffle/global");
}

function shuffleColor(value) {
	local.send("/deferlante/shuffle/color");
}

function shuffleMirror(value) {
	local.send("/deferlante/shuffle/mirror");
}

function shuffleBlur(value) {
	local.send("/deferlante/shuffle/blur");
}

function shuffleLasers(value) {
	local.send("/deferlante/shuffle/lasers");
}

function shuffleSpot(value) {
	local.send("/deferlante/shuffle/spot");
}

function shuffleAudio(value) {
	local.send("/deferlante/shuffle/audio");
}

function shuffleSphere(value) {
	local.send("/deferlante/shuffle/sphere");
}

function shuffleWarp(value) {
	local.send("/deferlante/shuffle/warp");
}

function triggerGlitch(value) {
	local.send("/deferlante/glitch_now");
}

function randomizeColors(value) {
	local.send("/deferlante/randomize");
}

function shuffle(value) {
	local.send("/deferlante/shuffle");
}
